main: com.daniel.commandexecutors.Main
name: CommandExecutors
description: MC command executors test
version: 1.0
commands:
  heal:
    description: heal yourself
  time:
    aliases: [get_time]
    description: Get the current time.