main: com.daniel.commandexecutors.Main
name: CommandExecutors
description: MC command executors test
version: 1.0
commands:
  heal:
    description: heal yourself
  feed:
    description: feed yourself
  time:
    aliases: [get_time]
    description: Get the current time.
  number:
    description: enter a number.
  consoleonly:
    description: can only be used in console
  fruit: